version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./my_sites.conf/:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
